[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
viaIR = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
base-mainnet = "https://mainnet.base.org"

[etherscan]
base-sepolia = { key = "${BASESCAN_API_KEY}" }
base-mainnet = { key = "${BASESCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
